environment:
  matrix:
    - arch: "x86-64"
      tools: "mingw"
    - arch: "x86-64"
      tools: "cygwin"

install:
  - ps: if($env:tools -eq 'mingw')
        {
          $env:c_comp = 'gcc';
        }
        elseif($env:tools -eq 'cygwin')
        {
          $env:c_comp = 'gcc';
        }

build_script:
  - IF [%tools%]==[mingw] set PATH=C:\mingw64\bin;%PATH%
  - IF [%tools%]==[mingw] sh -c "%c_comp% -v && ./configure CC=%c_comp% && make" 
  - IF [%tools%]==[cygwin] set PATH=C:\cygwin64\bin;%PATH%
  - IF [%tools%]==[cygwin] sh -c "%c_comp% -v && ./configure CC=%c_comp% && make"
